/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mattiameligeni.gestionebanca;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mattiakdm
 */
public class GUI extends javax.swing.JFrame {
    private boolean uso = false;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedMain = new javax.swing.JTabbedPane();
        TabbedUtentiEsistenti = new javax.swing.JTabbedPane();
        PanelSceltaUtente = new javax.swing.JPanel();
        C_SceltaUtente = new javax.swing.JComboBox<>();
        B_Carica = new javax.swing.JButton();
        B_ScegliUtente = new javax.swing.JButton();
        B_Ricarica = new javax.swing.JButton();
        PanelDatiUtente = new javax.swing.JPanel();
        L_NomeCompleto = new javax.swing.JLabel();
        T_Nome = new javax.swing.JTextField();
        L_CFiscale = new javax.swing.JLabel();
        T_CFiscale = new javax.swing.JTextField();
        L_AConto = new javax.swing.JLabel();
        T_AConto = new javax.swing.JTextField();
        L_Saldo = new javax.swing.JLabel();
        T_Saldo = new javax.swing.JTextField();
        B_Indietro = new javax.swing.JButton();
        TabbedNuovoUtente = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        B_Carica.setText("Carica utenti");
        B_Carica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CaricaActionPerformed(evt);
            }
        });

        B_ScegliUtente.setText("Scegli utente");
        B_ScegliUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ScegliUtenteActionPerformed(evt);
            }
        });

        B_Ricarica.setText("Ricarica utenti");
        B_Ricarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RicaricaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSceltaUtenteLayout = new javax.swing.GroupLayout(PanelSceltaUtente);
        PanelSceltaUtente.setLayout(PanelSceltaUtenteLayout);
        PanelSceltaUtenteLayout.setHorizontalGroup(
            PanelSceltaUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSceltaUtenteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelSceltaUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_Carica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Ricarica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(PanelSceltaUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_ScegliUtente, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(C_SceltaUtente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelSceltaUtenteLayout.setVerticalGroup(
            PanelSceltaUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSceltaUtenteLayout.createSequentialGroup()
                .addGroup(PanelSceltaUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_SceltaUtente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Carica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSceltaUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_ScegliUtente)
                    .addComponent(B_Ricarica))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabbedUtentiEsistenti.addTab("Scegli utente", PanelSceltaUtente);

        L_NomeCompleto.setText("Nome completo:");

        T_Nome.setEditable(false);

        L_CFiscale.setText("Codice fiscale:");

        T_CFiscale.setEditable(false);

        L_AConto.setText("Apertura conto:");

        T_AConto.setEditable(false);

        L_Saldo.setText("Saldo:");

        T_Saldo.setEditable(false);

        B_Indietro.setText("Indietro");
        B_Indietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IndietroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatiUtenteLayout = new javax.swing.GroupLayout(PanelDatiUtente);
        PanelDatiUtente.setLayout(PanelDatiUtenteLayout);
        PanelDatiUtenteLayout.setHorizontalGroup(
            PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatiUtenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_Indietro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelDatiUtenteLayout.createSequentialGroup()
                        .addGroup(PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_NomeCompleto)
                            .addComponent(L_CFiscale)
                            .addComponent(L_AConto)
                            .addComponent(L_Saldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T_Nome)
                            .addComponent(T_AConto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(T_CFiscale, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(T_Saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PanelDatiUtenteLayout.setVerticalGroup(
            PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatiUtenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_NomeCompleto)
                    .addComponent(T_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_CFiscale)
                    .addComponent(T_CFiscale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_AConto)
                    .addComponent(T_AConto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatiUtenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Saldo)
                    .addComponent(T_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(B_Indietro)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        TabbedUtentiEsistenti.addTab("Dati utente", PanelDatiUtente);

        TabbedMain.addTab("Utenti Esistenti", TabbedUtentiEsistenti);
        TabbedMain.addTab("Crea nuovo utente", TabbedNuovoUtente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedMain, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CaricaActionPerformed
        try {
            CaricaComboUtenti();
            B_Carica.setEnabled(false);
            B_Ricarica.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_B_CaricaActionPerformed

    private void B_ScegliUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ScegliUtenteActionPerformed
        TabbedUtentiEsistenti.setSelectedComponent(PanelDatiUtente);
        uso = true;
        try {
            CaricaDati();
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_B_ScegliUtenteActionPerformed

    private void B_IndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IndietroActionPerformed
        
        TabbedUtentiEsistenti.setSelectedComponent(PanelSceltaUtente);
        if (uso==true){
            B_Ricarica.setEnabled(true);
        
        }
            
        
    }//GEN-LAST:event_B_IndietroActionPerformed

    private void B_RicaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RicaricaActionPerformed
        C_SceltaUtente.removeAllItems();
        try {
            CaricaComboUtenti();
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_B_RicaricaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        B_Ricarica.setEnabled(false);
        T_Nome.setText("Scegli un utente per poter vedere i dati.");
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
    }

    private void CaricaComboUtenti() throws IOException {

        String file = "/home/mattiakdm/NetBeansProjects/GestioneBanca/src/main/java/com/mattiameligeni/gestionebanca/utenti.txt";
        try (FileInputStream fstream = new FileInputStream(file)) {
            BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
            String strNome;

            while ((strNome = br.readLine()) != null) {

                for (int i = 0; i < strNome.length(); i++) {
                    
                    if(strNome.charAt(i) == '#'){
                    
                        strNome = strNome.substring(0, i);
                        C_SceltaUtente.addItem(strNome);
                        break;
                        
                        
                    }
                    
                }

            }

        }

    }
    
    private void CaricaDati() throws IOException{
        String utente = (String)C_SceltaUtente.getSelectedItem();
        String file = "/home/mattiakdm/NetBeansProjects/GestioneBanca/src/main/java/com/mattiameligeni/gestionebanca/utenti.txt";
        try (FileInputStream fstream = new FileInputStream(file)) {
            BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
            String strNome = "";
            String strCF = "";
            String AC = "";
            String S = "";
            String record;
            int tmp = 0;
            while ((record = br.readLine()) != null) {
                if(!(record.contains(utente))){
                    
                    continue;
                    
                }
                for (int i = 0; i < record.length(); i++) {
                    
                    if(record.charAt(i) == '#'){
                        
                        if(strNome.equals("")){
                            
                            strNome = record.substring(0, i);
                            T_Nome.setText(strNome);
                        } 
                        if(strCF.equals("")){
                        
                            strCF = record.substring(i+1, i+17);
                            T_CFiscale.setText(strCF);
                            tmp = i+17;
                        }
                        if(AC.equals("")){
                        
                            AC = record.substring(tmp+1, tmp+11);
                            T_AConto.setText(AC);
                            tmp = i+28;
                        }
                        if(S.equals("")){
                        
                            S = record.substring(tmp+1);
                            T_Saldo.setText(S);
                        }
                        
                        break;
                        
                        
                    }
                    
                }

            }

        }
        
    }
    
    private void PulisciDati(){
    
        T_AConto.setText("");
        T_CFiscale.setText("");
        T_Nome.setText("");
        T_Saldo.setText("");
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Carica;
    private javax.swing.JButton B_Indietro;
    private javax.swing.JButton B_Ricarica;
    private javax.swing.JButton B_ScegliUtente;
    private javax.swing.JComboBox<String> C_SceltaUtente;
    private javax.swing.JLabel L_AConto;
    private javax.swing.JLabel L_CFiscale;
    private javax.swing.JLabel L_NomeCompleto;
    private javax.swing.JLabel L_Saldo;
    private javax.swing.JPanel PanelDatiUtente;
    private javax.swing.JPanel PanelSceltaUtente;
    private javax.swing.JTextField T_AConto;
    private javax.swing.JTextField T_CFiscale;
    private javax.swing.JTextField T_Nome;
    private javax.swing.JTextField T_Saldo;
    private javax.swing.JTabbedPane TabbedMain;
    private javax.swing.JTabbedPane TabbedNuovoUtente;
    private javax.swing.JTabbedPane TabbedUtentiEsistenti;
    // End of variables declaration//GEN-END:variables
}
